### ISSUE TITLE
Quorum Client on Rpi

### ISSUE THREAD

**Issue by malek87** [vjrantal/telemetry-contract#2]
How do you install quorum on a rpi?

**Comment by vjrantal** [comment]
@malek87 I built quorum on the rpi from sources.

If you decide to go that route and have issues compiling, I suggest opening an issue in the quorum repository.

Closing the issue on this repository, but feel free to re-open if you think there is something to fix here.

**Comment by malek87** [comment]
Thank you. Can you provide the constellation package for raspberry? It would be very useful to recreate your telemetry example from youtube.

**Comment by vjrantal** [comment]
@malek87 I don't have the built package anymore handy and it would be a pretty old version anyways. I would recommend trying to get it built yourself.

**Comment by Kavya9294** [comment]
Can you please provide instructions on how you built Constellation package on Raspberry Pi. That would really help.
